var lessons = [
    {
        "id":101,
        "subject":"English",
        "location":"Bauchi",
        "price":280,
        "availableInventory":5,
        "image": "images/eng.jfif"
    },
    {
        "id":102,
        "subject":"Mathematics",
        "location":"Lagos",
        "price":215,
        "availableInventory":5,
        "image":"images/maths.jfif"   
    },
    {
        "id":103,
        "subject":"Chemistry",
        "location":"Abuja",
        "price":230,
        "availableInventory":5,
        "image":"images/chem.jfif"   
    },
    {
        "id":104,
        "subject":"Physics",
        "location":"Kwara",
        "price":110,
        "availableInventory":5,
        "image":"images/physics.jfif"   
    },
    {
        "id":105,
        "subject":"Arabic",
        "location":"Sokoto",
        "price":150,
        "availableInventory":5,
        "image":"images/arabic.jfif"   
    },
    {
        "id":106,
        "subject":"Hausa",
        "location":"Kano",
        "price":200,
        "availableInventory":5,
        "image":"images/img6.jpg"   
    },
    {
        "id":107,
        "subject":"Music",
        "location":"Osun",
        "price":110,
        "availableInventory":5,
        "image":"images/music.jfif"   
    },
    {
        "id":108,
        "subject":"Programming",
        "location":"Ogun",
        "price":120,
        "availableInventory":5,
        "image":"images/programming.jfif"   
    },
    {
        "id":109,
        "subject":"Agric Science",
        "location":"Katsina",
        "price":180,
        "availableInventory":5,
        "image":"images/agric.jfif"   
    },
    {
        "id":110,
        "subject":"Social Studies",
        "location":"Kaduna",
        "price":100,
        "availableInventory":5,
        "image":"images/social.jfif"   
    }
]